### ISSUE TITLE
Action fails if repository is unshallow 

### ISSUE THREAD

**Issue by adrianimajion** [GeoWerkstatt/create-jira-release#12]
If the workflow has already checked out an unshallow repository in an earlier step, this action will fail in the first step when calling running git fetch --prune --unshallow --tags.

I've made a small pull request to fix this issue here: https://github.com/GeoWerkstatt/create-jira-release/pull/11

**Comment by gamoreli** [comment]
hey guys, could you please merge @adrianimajion code?
